<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\DocFxHelper.Infrastructure\DocFxHelper.Infrastructure.csproj" />
    <ProjectReference Include="..\DocFxHelper.Abstractions\DocFxHelper.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Run\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.1.1" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
