using System;
using System.Collections.Generic;
using System.Text;

namespace DocFxHelper.Core.Specs
{

  /// <summary>
  /// Specifies the supported types of documentation sources that can be processed by DocFxHelper.
  /// </summary>
  /// <remarks>Each value in the enumeration represents a distinct format or origin of documentation, such as
  /// Azure DevOps wikis, .NET APIs, REST API specifications, PowerShell modules, conceptual markdown content, Mustache
  /// templates, or DocFx-generated API YAML files. The processing pipeline in DocFxHelper handles each source type
  /// according to its specific requirements and structure.</remarks>
  public enum SourceType
  {

    /// <summary>
    /// The source is an AdoWiki, which is a wiki hosted in Azure DevOps. The source files will be published from the wiki via a pipeline and processed by DocFxHelper.
    /// </summary>
    AdoWiki,

    /// <summary>
    /// The source is a dotnet API, which is a set of .NET assemblies. The source files will be generated from the assemblies via a pipeline and processed by DocFxHelper.
    /// </summary>
    DotnetApi,

    /// <summary>
    /// The source is a RESTS API documentation in the form of a swagger.json file.
    /// </summary>
    /// <see cref="https://dotnet.github.io/docfx/docs/rest-api-docs.html"/>    
    RestApi,

    /// <summary>
    /// The source is a PowerShell module, which is a set of PowerShell scripts and cmdlets.  DocFxHelper expects the module to include the source files, including the .psd1, .psm1 and any other file.
    /// </summary>
    PowerShellModule,

    /// <summary>
    /// The source is a classic DocFx conceptual documentation, which is a set of markdown files organized in a folder structure. The source files will be processed by DocFxHelper as is.
    /// </summary>
    Conceptual,

    /// <summary>
    /// The source is a set of Mustache templates, which are used to generate conceptual documentation from other sources. The source files will be processed by DocFxHelper and used as templates for generating markdown files.
    /// </summary>
    Template,

    /// <summary>
    /// The source is an dotnet API documentation in the form of an API YAML file, which is generated by DocFx from .NET assemblies using the command line argument --build and --exportRawModel. The source files will be processed by DocFxHelper to generate conceptual documentation.
    /// </summary>
    YamlApi

  }
}
